### PR TITLE
Create project model independent of config file structure

### PR DESCRIPTION
**Pull request by foip**
I'm not sure if this is reasonable or overkill.
Also I didn't want to merge to upstream, because you're 40 commits ahead and I didn't want to interfere too much.

## Changes

I implemented a `project_model` structure, that is (for now) almost identical to the `config_file` structure.
I also pulled the selection of defaults for missing configuration values from the `build` functions to the `load_model` function inside `utils`.

## Why

A few reasons:

* It gives a reasonable place for defaults:
You would have to choose the defaults for missing configuration values inside every zork command (`build`, `run`, `test`...).
Now it all happens in one central place when the configuration is loaded.
* Cleaner Code on the call site:
Choosing reasonable defaults early on avoids lots of the `Option<T>` that are present, thus avoiding a lot of `if let Some(_)` in the calling code.
* It is independent of the `zork.toml` Syntax (Separation of concerns):
This gives flexibility to change and extend the model without breaking file syntax. For example strong typing for some fields.
This becomes more important if we want to split the configuration into more files, for example if we choose to support subprojects or submodules of some kind.

## Other considerations
 
I made the entire structure owning, using `String`s instead of `&str`s.
Mostly because it is convenient from the API perspective (less worry about lifetime annotations).

I'm not too worried about performance.
The allocations happen once at startup, and (to be honest) we're throwing around with `Vec`s anyway.

### CODE REVIEW

**Comment by foip** [comment]
Also sorry that it's all in one commit, but there was no point in between, where it was compilable.

**Comment by TheRustifyer** [comment]
Hello! And sorry for taking too long on answering this.

I was thinking about all the proposed changes since I've noticed this PR. Here are my thoughts:

- At first glance, I didn't really liked the "separation of concerns" way of having some kind of `domain-driven` architecture for such an small application. This means, I didn't like (and still I don't like too much) the idea of having entities to parse the config file, and then mapping their content to a new ones. It sounds to me like the classical Java way of dealing with domain problems , and it seems really overkill for such an small binary. Even tho we have a separation between library components and a binary entry, this only answers to the need of writing integration tests later (for the "library code").
- Comming back to the main flow, for me the data declared on the configuration file might be coupled literally with the main flux (parsing it, and then processing it).
- quote: "This gives flexibility to change and extend the model without breaking file syntax. For example strong typing for some fields." - True. But a way of avoid coupling could also be like the `Argument<'a>` structure. Argument knows nothing about the config file. It is completly decoupled from anything that is not taking `String` or `&str`.
- quote: "This becomes more important if we want to split the configuration into more files, for example if we choose to support subprojects or submodules of some kind." This is a true reallity. Also, I wanted to support multiple config files for different compilers in the same project (for example: zork_clang.toml and zork_gcc.toml), and process them sequentially. Also, I would like to offer some suffixes, like (zork_clang_pre.toml and zork_gcc_pro). But always being defined what are available to be parsed.

But thinking further, I also like your changes (it's been difficult to me knowing my real feelings about the whole proposal)
- I like the initialization of default values
- I like the overall structure of dealing with the strong typing for some of them (we can even go further and apply the new type patter over `Vec<Argument>` as `Arguments`, for example. That's something that is already planned, but my time is limited and I am not able of focusing on too many things.
- I like the way of having the real data known before hand, and the overall look of the `ZorkModel`.
- I miss the lifetime annotations. They aren't a real problem on our code, mostly because all code is mostly sequential, and all the data lives the necessary time. Most of the parameters are literally `&'static str, so there's no need to allocate them.
- True that we are dealing anyway with vecs. But one of the future changes is to pass them around as `&Vec<T>` or better, `&[T]`. This still hasn't been applied because my primary focus now it's to be able to fully support the three major compilers. Then refactor the code. Then optimize it (if possible). Pre-allocating everything will make much more difficult the later task, so I tried to mantain a balance between the approaches.

For the sake of completness, I would like to provide integration tests and bechmarks. Also, true that the performance isn't the main concern of this application (parse a single translation unit could be much more expensive than our full process), but that doesn't means to forget about it. One fun thing of Rust (at least for me) is to focus (better latter than sonner) on this things.

I would prefer also, to delegate job on trait bounds and generic parse functions (even tho that they must allocate resources finally) for the whole code style. Take a look at the `add_extra_args_if_present<T>(...)` method, and see if they are applicable to this PR.

In the overall, I admit that finally, I liked your changes, as usual, but I would like to find a balance between the way of dealing things with the `ZorkModel` approach, and the more functional.

For that, I merged your changes into latest mines, and they live in a new branch in my repo, `foip-feature/GH-45...`. Take a look at them, and I would like to read your thoughts about everything in general.

Also, I encourage you to enter our Discord server, were we can make better discussions about changes before hand, and have the work more aligned between different perspectives. https://discord.gg/R5B3QQ2Z

Finally, this weekend I would like to focus on merge your idea into the latest changes, and keep the app as much performant as it could be, but also, being more readable and mantainable as your approach does.
-

**Comment by foip** [comment]
> It sounds to me like the classical Java way of dealing with domain problems

I kinda come from a Java background so that might be true.

> having entities to parse the config file, and then mapping their content to a new ones.

I would argue that replacing all the `Option`s with defaults is more of an enrichment to the model rather than a simple mapping.
As you yourself argued:

> I like the way of having the real data known before hand

> But a way of avoid coupling could also be like the Argument<'a> structure.

I would argue that `Argument` and `Command` would also fit as part of the `project_model`. Running external commands is a functionality that is needed by all commands (`new`, `build`, `test`, `run`).

> Take a look at the `add_extra_args_if_present<T>(...)` method, and see if they are applicable to this PR

Same as above. I'd put `ExtraArgs` in the project model and put the method as default implementation on the trait.

> I miss the lifetime annotations.
They aren't a real problem on our code, mostly because all code is mostly sequential, and all the data lives the necessary time.
Most of the parameters are literally `&'static str, so there's no need to allocate them.

That was the only part where I myself was really unsure.
The parameters being `&'static str` is only true for the defaults.
The parsed parameters are bound by the lifetime of the `String` returned by `find_config_file`.

That means the model is valid as long as the content of the config file(s) lives as `String` in memory.
This is not a huge problem.
I just personally decided that I didn't want to bother.
But that change should be easy enough.

**Comment by TheRustifyer** [comment]
I will really wanted to see those changes, if possible. I would feel more comfortable respecting everything with its original lifetimes, and save possible allocations when necessary, ie: when `Argument::from` consumes an `&str`. The current implementation: 
```
impl<'a> From<&'a str> for Argument<'a> {
    fn from(value: &'a str) -> Self {
        Self { value }
    }
}

impl<'a> From<String> for Argument<'a> {
    fn from(value: String) -> Argument<'a> {
        Self { value: Box::leak(value.into_boxed_str()) }
    }
}
```
I don't really mind about leaking those `String`, as they always will remains as valid references, and will provide the same flexibility as `String` for our purposes. And, for sure, they won't be allocated again (just for the moment that they are created), typically when we are formatting argument or paths. 

> I would argue that replacing all the Options with defaults is more of an enrichment to the model rather than a simple mapping.

Yes, completly agree. Specially because all the "hard" work of dealing with the `Option<T>` are made before-hand, and the code responsable for processing things is much more cleaver, as you said in your first commentary.

> Same as above. I'd put ExtraArgs in the project model and put the method as default implementation on the trait.

This is the unique point that I don't like. I usually want (not always is possible) to treat traits as higher abstractions, trying to put them as far is possible for the domain problems. Even tho `ExtraArgs` tries to solve generically the problem of retrive the `extra_arguments` property for a config file model, or for a domain model, it could be used for retrieve any other optional property in a future. Or even being the same `ExtraArgs`, being enough flexible for other purposes. 
The Java's `hexagonal` arquitecture is a really good way of solving the classical domain problems, and traits could be represented as the adapter contracts, for example, complete decoupled from the domain.
I put them in a new file called `bounds.rs`, just for the sake of simplicity for now, but I still would like to make them "higher abstractions" (if applies and is a proper thing to do in a nearly future).

With that said, I would really like to see your changes merged with the latest ones (where the three major compilers are able to produce binaries). I would suggest you to finish those changes, and them try to merge into those latest changes, because probably you will do a better job merging my changes into yours.

Those changes are the last commit in the branch that you are pointing in this PR.

Thanks for your effort again.

**Pull request closed without merging**
